### ISSUE TITLE
Crashes on double code load

### ISSUE THREAD

**Issue by lukyanov** [basho/cluster_info#10]
Here are the steps to reproduce:

$ git co https://github.com/basho/cluster_info.git
$ cd cluster_info/
$ make
$ erl -pa ebin/
Erlang R15B01 (erts-5.9.1) [source] [64-bit] [smp:4:4] [async-threads:0] [hipe] [kernel-poll:false]

Eshell V5.9.1  (abort with ^G)
1> application:start(sasl).
ok
2> application:start(cluster_info).
ok
3> {Mod, Bin, File} = code:get_object_code(cluster_info).
{cluster_info,<<70,79,82,49,0,0,42,228,66,69,65,77,65,116,
                111,109,0,0,4,137,0,0,0,101,12,99,108,...>>,
              "/home/snaky/deps/cluster_info/ebin/cluster_info.beam"}
4> code:load_binary(Mod, File, Bin).
{module,cluster_info}
5> code:load_binary(Mod, File, Bin).
{module,cluster_info}
6>
=CRASH REPORT==== 26-Oct-2012::12:56:34 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.44.0>
    registered_name: []
    exception exit: killed
      in function  application_master:terminate/2 (application_master.erl, line 229)
    ancestors: [<0.43.0>]
    messages: []
    links: [<0.6.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 233
    stack_size: 24
    reductions: 1524
  neighbours:

=INFO REPORT==== 26-Oct-2012::12:56:34 ===
    application: cluster_info
    exited: killed
    type: temporary

**Comment by slfritchie** [comment]
Due to code-in-use while the application is running, this behavior is expected.  Closing old ticket, sorry for letting this languish in open state for so long.
